# Generated by Django 5.2.8 on 2025-11-25 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_api", "0004_todotask_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todotask",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddIndex(
            model_name="todotask",
            index=models.Index(
                fields=["user", "completed"], name="task_api_to_user_id_e11164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todotask",
            index=models.Index(
                fields=["user", "updated"], name="task_api_to_user_id_e0b9d4_idx"
            ),
        ),
    ]
